services:
  frontend:
    build:
      context: ../brighter-frontend
      target: deps
    command: sh -c "bun install && bun run dev -- --host 0.0.0.0 --port 3000"
    environment:
      VITE_TURNSTILE_SITE_KEY: ${VITE_TURNSTILE_SITE_KEY}
    volumes:
      - ../brighter-frontend:/app
      - bun-cache:/root/.bun/install/cache
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.services.frontend-svc.loadbalancer.server.port=3000"

  admin-panel:
    build:
      context: ../brighter-admin-panel
      target: deps
    command: sh -c "bun install && bun run dev -- --host 0.0.0.0 --port 5173"
    volumes:
      - ../brighter-admin-panel:/app
      - bun-cache:/root/.bun/install/cache
    environment:
      VITE_BASENAME: "/admin"
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=PathPrefix(`/admin`)"
      - "traefik.http.routers.admin.entrypoints=web"
      - "traefik.http.routers.admin.priority=10" # Higher priority than root
      - "traefik.http.services.admin-svc.loadbalancer.server.port=5173"
      
      # 1. Define Middleware: If user hits /admin, redirect to /admin/
      - "traefik.http.middlewares.admin-slash.redirectregex.regex=^(.*)/admin$$"
      - "traefik.http.middlewares.admin-slash.redirectregex.replacement=$${1}/admin/"
      - "traefik.http.middlewares.admin-slash.redirectregex.permanent=true"
      
      # 2. Apply Middleware to the router
      - "traefik.http.routers.admin.middlewares=admin-slash"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - backend
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_LOGIN:-admin@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD:-admin}

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - backend


volumes:
  bun-cache:
  pgadmin-data:
