global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: users-ms
    static_configs:
      - targets: ['users-ms:8000']
    metrics_path: /metrics

  - job_name: properties-ms
    static_configs:
      - targets: ['properties-ms:8001']
    metrics_path: /metrics

  - job_name: bookings-ms
    static_configs:
      - targets: ['bookings-ms:8002']
    metrics_path: /metrics

  - job_name: payments-ms
    static_configs:
      - targets: ['payments-ms:8003']
    metrics_path: /metrics

  - job_name: notifications-ms
    static_configs:
      - targets: ['notifications-ms:8004']
    metrics_path: /metrics

  - job_name: ai-ms
    static_configs:
      - targets: ['ai-ms:8005']
    metrics_path: /metrics

  - job_name: otel-collector
    static_configs:
      - targets: ['otel-collector:8888']
    metrics_path: /metrics
